### ISSUE TITLE
Word Count for Repository

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/uw-word-count#2]
This component should accept a DCS repository and generate a word count for that project.  Examples that should work:

* https://git.door43.org/unfoldingWord/en_tn/
* https://git.door43.org/unfoldingWord/en_ta/
* https://git.door43.org/unfoldingWord/en_tw/
* https://git.door43.org/unfoldingWord/en_obs/
* https://git.door43.org/unfoldingWord/en_obs-sn/
* https://git.door43.org/unfoldingWord/en_obs-sq/
* https://git.door43.org/unfoldingWord/en_obs-tn/
* https://git.door43.org/unfoldingWord/en_obs-tq/
* https://git.door43.org/unfoldingWord/en_ult/
* https://git.door43.org/unfoldingWord/en_ust/
* https://git.door43.org/unfoldingWord/el-x-koine_ugnt/
* https://git.door43.org/unfoldingWord/hbo_uhb/

Input can be a URL.

**Comment by mandolyte** [comment]
@jag3773 this requirement has a significant problem! The repos have varying ways to "find" the words. For example, some are `usfm` format and must be not only converted to JSON, but must be recursively processed; the UTN requires narrowing to column 8. 

All have files/directories that should be excluded from the count (yaml, .gitignore, etc.). This logic is built into the book package components, not word count.

The word count merely takes a string as input...

How do you want this work?

**Comment by jag3773** [comment]
generally, I think all that logic should be moved into the word count module. That would make it possible for other applications to successfully utilize this component, including the book package app.

**Comment by mandolyte** [comment]
**Background**
The book package app needs to look _inside_ the repo for specific books/chapters. How that is done varies by the type of repo, whether `_tn`, `_tw`, `_tq`, the two original texts, etc.

I use Klappy's APIs a lot and they are much more granular than a URL. He builds up the URL from the following:

- the owner (always `unfoldingWord`)
- the language id (for book package I hard coded `en`)
- the resource type (tn, tq, ult, ust, ta, tw, with special treatment for the two original text repos)
- he uses the manifests a lot in order to locate which file is which book (he does a lookup where the project matches the bookId)

**With the above in mind, how about a counter proposal:**

Allow the input URL to be any URL, not just to the repo. Thus these would be allowed:
```
https://git.door43.org/unfoldingWord/en_ta/
https://git.door43.org/unfoldingWord/en_ta/translate
https://git.door43.org/unfoldingWord/en_ta/translate/figs-metaphor
https://git.door43.org/unfoldingWord/en_ta/translate/figs-metaphor/01.md
```
These would be rules:

- If the URL is to the repo, then the resource type would be used to qualify what is counted. For example for `en_ta`, only the folder `translate` would be counted. The other folders would be ignored. In some other cases, only the `content` folder would be counted.
- If the URL is to a folder within a repo, then the folder would be recursively processed and each "qualifying" file type counted.
- A "qualifying" file type is one that has the expected extension for the type of resource.
- UTA, UTW: type is ".md"
- ULT, UST, and Original Language type is ".usfm"
- UTN is ".tsv" and only column 8 (? confirm)
- OBS looks like ".md"; possibly the other OBS resources are too?

**What this means for the book package app:**

- For some resource types it has look _inside_ the files for chapters, it will be able to use the "basic" word count component, but not the "repo" word count component.
- For the other resource types it will be able to use the "repo" version, by extending the path to the specific chapter folders.

**Comment by jag3773** [comment]
Perfect!  It would be helpful to be able to know the word count for only the translation manual, for example.

**Comment by mandolyte** [comment]
@jag3773 Question: Should I allow any URL that does NOT begin with `https://git.door43.org/unfoldingWord/`? I suspect not since our code probably shouldn't be used to count words from arbitrary internet locations. Then the question becomes, do we restrict this to only unfoldingWord or should this be able to count words in any DCS location?

If we shouldn't take arbitrary URLs, then maybe the component should be like:
```
<WordCountRepo owner="unfoldingWord" repo="en_ta" path="/translate/figs-metaphor/" />
``

Of course, I could still take a URL, but if we need the restrictions, then I can validate the URL. However, breaking down the pieces would allow me to easily use https://git.door43.org/api/swagger#/repository/GetTree, which I think I need to in order to get all the files in a repo or beneath a folder in a repo.

Even if they want to count words in a single file, the tree api allows me to easily let the user know if they have mistyped the filename. I can avoid the whole issue of 404s that the book package currently has.

Thoughts?

**Comment by jag3773** [comment]
Any repo on git.door43.org is good.  Ideally this can be integrated/work with https://gitea-react-toolkit.netlify.com/repositories -- but that may come later at the app stage.

Per file word counts would be great.

**Comment by jag3773** [comment]
@mandolyte Has this issue been completed, or are there aspects that still need worked on?  Do each of the initially listed repos work as expected?

**Comment by mandolyte** [comment]
That's correct... non-english scripts will not work. JavaScript regex only work on Latin scripts; maybe not even UTF-8, just ASCII.
